# Generated by Django 4.2.7 on 2026-04-28 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("executions", "0002_initial"),
        ("versions", "0001_initial"),
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_runs",
                to="versions.version",
                verbose_name="关联版本",
            ),
        ),
        migrations.AddField(
            model_name="testplan",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="指派给",
            ),
        ),
        migrations.AddField(
            model_name="testplan",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="testplan",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="test_plans",
                to="projects.project",
                verbose_name="关联项目",
            ),
        ),
        migrations.AddField(
            model_name="testplan",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_plans",
                to="versions.version",
                verbose_name="关联版本",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testruncase",
            unique_together={("test_run", "testcase")},
        ),
    ]
