# Generated by Django 4.2.7 on 2026-04-28 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("explorations", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorationrun",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exploration_runs",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="explorationartifact",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="explorations.explorationrun",
            ),
        ),
    ]
