# Generated by Django 4.2.7 on 2026-04-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorationrun",
            name="auth_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="explorationrun",
            name="auth_type",
            field=models.CharField(default="none", max_length=20),
        ),
        migrations.AddField(
            model_name="explorationrun",
            name="auth_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="explorationrun",
            name="base_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="explorationrun",
            name="max_steps",
            field=models.IntegerField(default=10),
        ),
    ]
