# Generated by Django 4.2.7 on 2026-04-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("versions", "0001_initial"),
        ("testcases", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="versions",
            field=models.ManyToManyField(
                blank=True,
                related_name="testcases",
                to="versions.version",
                verbose_name="关联版本",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testcasestep",
            unique_together={("testcase", "step_number")},
        ),
    ]
